export const TRACKS = {
  monza: {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    shortName: 'Monza',
    country: 'ITA',
    countryName: 'Italy',
    svgPath: '/RaceCircuitAutodromaDiMonza.svg',
    jolpicaCircuitId: 'monza',
    openF1: {
      circuitShortNames: ['Monza'],
      countryName: 'Italy',
    },
    stats: {
      length: '5.793 km',
      firstGP: '1950',
      laps: '53',
      lapRecord: { time: '1:20.097', driver: 'Rubens Barrichello (2004)' },
    },
    sectors: [
      {
        id: 'sector1',
        name: 'Sector 1',
        color: '#FF1E46',
        label: 'SECTOR 1',
        corners: [1, 2, 3],
        pathRange: { start: 0, end: 0.33 },
      },
      {
        id: 'sector2',
        name: 'Sector 2',
        color: '#00E5FF',
        label: 'SECTOR 2',
        corners: [4, 5, 6, 7],
        pathRange: { start: 0.33, end: 0.6 },
      },
      {
        id: 'sector3',
        name: 'Sector 3',
        color: '#FFF01E',
        label: 'SECTOR 3',
        corners: [8, 9, 10, 11],
        pathRange: { start: 0.6, end: 1 },
      },
    ],
    corners: [
      { id: 1, name: 'T1 Variante del Rettifilo', number: '01', trackPosition: 0.08 },
      { id: 2, name: 'T2 Variante del Rettifilo', number: '02', trackPosition: 0.11 },
      { id: 3, name: 'T3 Curva Grande', number: '03', trackPosition: 0.22 },
      { id: 4, name: 'T4 Variante della Roggia', number: '04', trackPosition: 0.34 },
      { id: 5, name: 'T5 Variante della Roggia', number: '05', trackPosition: 0.38 },
      { id: 6, name: 'T6 Lesmo 1', number: '06', trackPosition: 0.44 },
      { id: 7, name: 'T7 Lesmo 2', number: '07', trackPosition: 0.52 },
      { id: 8, name: 'T8 Variante Ascari', number: '08', trackPosition: 0.62 },
      { id: 9, name: 'T9 Variante Ascari', number: '09', trackPosition: 0.67 },
      { id: 10, name: 'T10 Variante Ascari', number: '10', trackPosition: 0.72 },
      { id: 11, name: 'T11 Curva Alboreto', number: '11', trackPosition: 0.88 },
    ],
    drsZones: [
      {
        id: 'drs1',
        name: 'DRS ZONE 1',
        detectionPosition: 0.5,
        activationPosition: 0.55,
        color: '#00FF41',
      },
      {
        id: 'drs2',
        name: 'DRS ZONE 2',
        detectionPosition: 0.92,
        activationPosition: 0.98,
        color: '#00FF41',
      },
    ],
    speedTrap: {
      trackPosition: 0.96,
      label: 'SPEED TRAP',
    },
    startFinish: {
      trackPosition: 0,
    },
  },

  silverstone: {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    shortName: 'Silverstone',
    country: 'GBR',
    countryName: 'United Kingdom',
    svgPath: '/RaceCircuitSilverstone.svg',
    jolpicaCircuitId: 'silverstone',
    openF1: {
      circuitShortNames: ['Silverstone'],
      countryName: 'United Kingdom',
    },
    stats: {
      length: '5.891 km',
      firstGP: '1950',
      laps: '52',
      lapRecord: { time: '1:27.097', driver: 'Max Verstappen (2020)' },
    },
    sectors: [
      {
        id: 'sector1',
        name: 'Sector 1',
        color: '#FF1E46',
        label: 'SECTOR 1',
        corners: [1, 2, 3, 4, 5, 6],
        pathRange: { start: 0, end: 0.33 },
      },
      {
        id: 'sector2',
        name: 'Sector 2',
        color: '#00E5FF',
        label: 'SECTOR 2',
        corners: [7, 8, 9],
        pathRange: { start: 0.33, end: 0.55 },
      },
      {
        id: 'sector3',
        name: 'Sector 3',
        color: '#FFF01E',
        label: 'SECTOR 3',
        corners: [10, 11, 12, 13, 14, 15, 16, 17, 18],
        pathRange: { start: 0.55, end: 1 },
      },
    ],
    corners: [
      { id: 1, name: 'T1 Abbey', number: '01', trackPosition: 0.02 },
      { id: 2, name: 'T2 Farm', number: '02', trackPosition: 0.06 },
      { id: 3, name: 'T3 Village', number: '03', trackPosition: 0.1 },
      { id: 4, name: 'T4 The Loop', number: '04', trackPosition: 0.15 },
      { id: 5, name: 'T5 Aintree', number: '05', trackPosition: 0.2 },
      { id: 6, name: 'T6 Wellington Straight', number: '06', trackPosition: 0.26 },
      { id: 7, name: 'T7 Brooklands', number: '07', trackPosition: 0.35 },
      { id: 8, name: 'T8 Luffield', number: '08', trackPosition: 0.42 },
      { id: 9, name: 'T9 Copse', number: '09', trackPosition: 0.52 },
      { id: 10, name: 'T10 Maggots', number: '10', trackPosition: 0.58 },
      { id: 11, name: 'T11 Becketts', number: '11', trackPosition: 0.62 },
      { id: 12, name: 'T12 Chapel', number: '12', trackPosition: 0.66 },
      { id: 13, name: 'T13 Hangar Straight', number: '13', trackPosition: 0.72 },
      { id: 14, name: 'T14 Stowe', number: '14', trackPosition: 0.78 },
      { id: 15, name: 'T15 Vale', number: '15', trackPosition: 0.84 },
      { id: 16, name: 'T16 Club', number: '16', trackPosition: 0.88 },
      { id: 17, name: 'T17 Club', number: '17', trackPosition: 0.92 },
      { id: 18, name: 'T18 Club', number: '18', trackPosition: 0.96 },
    ],
    drsZones: [
      {
        id: 'drs1',
        name: 'DRS ZONE 1',
        detectionPosition: 0.4,
        activationPosition: 0.48,
        color: '#00FF41',
      },
      {
        id: 'drs2',
        name: 'DRS ZONE 2',
        detectionPosition: 0.68,
        activationPosition: 0.74,
        color: '#00FF41',
      },
    ],
    speedTrap: {
      trackPosition: 0.75,
      label: 'SPEED TRAP',
    },
    startFinish: {
      trackPosition: 0,
    },
  },
};

export const TRACK_LIST = Object.values(TRACKS);
